name: Release

on:
  workflow_dispatch:

  push:
    branches: main
    paths-ignore: 
      - CHANGELOG.md
      - pyproject.toml
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: read and write
      contents: read and write
      pull-requests: read and write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
